### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by torgeirl** [juju/guiproxy#28]
The usage section of `juju/guiproxy/README.md` is short and without much detail.

Could someone please extend it, so someone outside the development team from reading the documentation can understand how this is intended to work? :pray: 

**Example**
How are you meant to get juju-gui to run in development mode? When running GUIProxy I get the error:
> Unable to create socketURL, no apiAddress provided. The GUI must be loaded with a valid configuration. Try GUIProxy if running in development mode: https://github.com/juju/guiproxy

`juju/juju-gui/docs/hacking.md` however states:
> In order to actually use the GUI in the development mode you will need to connect it to a Juju Controller. To do this we use GUIProxy, see its Readme for information on how to use and build it.

So I should:
1. try GUIProxy if I'm running [juju-gui] in development mode
2. and to run it in development mode I should use GUIProxy :thinking:

**Comment by hatched** [comment]
From the information provided it looks like you're trying to access the GUI from the GUI server url and not the `guiproxy` url.

When you start the `guiproxy`  you should have an output like...
```
...
2018/07/26 10:37:39 visit the GUI at any of the following addresses:
  http://127.0.0.1:8042/
  http://192.168.64.6:8042/
```

You'll want to visit one of those IP's and not the ones from the GUI.

We'll have to expand the documentation a bit to make that clearer.

**Comment by torgeirl** [comment]
@hatched: oh, no wonder it didn't work.

Thanks for the quick reply. Expended docs would be much appreciated!
